# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'archive_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class archive_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(585, 453)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListWidget(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(30, 30, 541, 361))
        self.listView.setObjectName("listView")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 380, 551, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.archive_export = QtWidgets.QPushButton(self.frame)
        self.archive_export.setGeometry(QtCore.QRect(450, 30, 93, 28))
        self.archive_export.setObjectName("archive_export")
        self.archive_delete = QtWidgets.QPushButton(self.frame)
        self.archive_delete.setGeometry(QtCore.QRect(10, 30, 93, 28))
        self.archive_delete.setObjectName("archive_delete")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.archive_export.setText(_translate("MainWindow", "Export"))
        self.archive_delete.setText(_translate("MainWindow", "delete"))


