# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dashboard_window(object):
    def setupUi(self, Dashboard_window):
        Dashboard_window.setObjectName("Dashboard_window")
        Dashboard_window.resize(585, 453)
        self.centralwidget = QtWidgets.QWidget(Dashboard_window)
        self.centralwidget.setObjectName("centralwidget")
        self.dashboard_list = QtWidgets.QListWidget(self.centralwidget)
        self.dashboard_list.setGeometry(QtCore.QRect(30, 30, 541, 351))
        self.dashboard_list.setObjectName("dashboard_list")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 390, 581, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.dashboard_delete_button = QtWidgets.QPushButton(self.frame)
        self.dashboard_delete_button.setGeometry(QtCore.QRect(380, 20, 93, 28))
        self.dashboard_delete_button.setObjectName("dashboard_delete_button")
        self.dashboard_archive_button = QtWidgets.QPushButton(self.frame)
        self.dashboard_archive_button.setGeometry(QtCore.QRect(470, 20, 93, 28))
        self.dashboard_archive_button.setObjectName("dashboard_archive_button")
        self.dashboard_deleteall_button = QtWidgets.QPushButton(self.frame)
        self.dashboard_deleteall_button.setGeometry(QtCore.QRect(20, 20, 93, 28))
        self.dashboard_deleteall_button.setObjectName("dashboard_deleteall_button")
        self.dashboard_archiveall_button = QtWidgets.QPushButton(self.frame)
        self.dashboard_archiveall_button.setGeometry(QtCore.QRect(110, 20, 93, 28))
        self.dashboard_archiveall_button.setObjectName("dashboard_archiveall_button")
        Dashboard_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Dashboard_window)
        QtCore.QMetaObject.connectSlotsByName(Dashboard_window)

    def retranslateUi(self, Dashboard_window):
        _translate = QtCore.QCoreApplication.translate
        Dashboard_window.setWindowTitle(_translate("Dashboard_window", "MainWindow"))
        self.dashboard_delete_button.setText(_translate("Dashboard_window", "delete"))
        self.dashboard_archive_button.setText(_translate("Dashboard_window", "archive"))
        self.dashboard_deleteall_button.setText(_translate("Dashboard_window", "delete all"))
        self.dashboard_archiveall_button.setText(_translate("Dashboard_window", "archive all"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dashboard_window = QtWidgets.QMainWindow()
    ui = Ui_Dashboard_window()
    ui.setupUi(Dashboard_window)
    Dashboard_window.show()
    sys.exit(app.exec_())
